language: bash
services: docker

env:
  - WORDPRESS_VERSION=5 PHP_VERSION=5.6
  - WORDPRESS_VERSION=5 PHP_VERSION=7.2
  - WORDPRESS_VERSION=5 PHP_VERSION=7.4

matrix:
  fast_finish: true

script:
  - docker --version
  - docker image build . -t marcortola/wordpress-tests:$WORDPRESS_VERSION-php$PHP_VERSION --build-arg PHP_VERSION=$PHP_VERSION --build-arg WORDPRESS_VERSION=$WORDPRESS_VERSION
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image push marcortola/wordpress-tests:$WORDPRESS_VERSION-php$PHP_VERSION

after_script:
  - docker image ls
