version: "3.3"

services:
  wordpress:
    image: marcortola/wordpress-tests:${WORDPRESS_VERSION:-5}-php${PHP_VERSION:-7.4}
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ./:/var/www/html/wp-content/themes/theme:ro
    environment:
      WORDPRESS_DB_HOST: "database"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: "database"
      WORDPRESS_DEBUG: 0

  database:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: ""
